# Generated by Django 4.2.4 on 2023-08-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('main_contact', models.CharField(max_length=100)),
                ('limit_time', models.TimeField()),
                ('city_labor', models.CharField(max_length=255)),
            ],
        ),
    ]
