# Generated by Django 4.2.4 on 2023-08-05 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=100)),
                ('dish_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dish_description', models.TextField()),
                ('dish_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_id', models.IntegerField()),
                ('order_status', models.CharField(choices=[('process', 'En Proceso'), ('accepted', 'Aceptado'), ('packed', 'Empacado'), ('shipped', 'Transportado'), ('delivered', 'Entregado')], default='process', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CartOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.order')),
            ],
            options={
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
