# Generated by Django 4.2.4 on 2023-08-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_cartorderitems_dish_delete_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('process', 'In Process'), ('accepted', 'Accepted'), ('packed', 'Packed'), ('shipped', 'Transported'), ('delivered', 'Delivered')], default='process', max_length=150),
        ),
    ]
